debug: false
demo: false
db: sqlite
mysql:
  hostname: localhost
  port: 3306
  username: next-terminal
  password: next-terminal
  database: next-terminal
sqlite:
  file: '/usr/local/next-terminal/data/sqlite/next-terminal.db'
server:
  addr: 0.0.0.0:8088
guacd:
  hostname: guacd
  port: 4822
  # 此路径需要为绝对路径，并且next-terminal和guacd都能访问到
  recording: '/usr/local/next-terminal/data/recording'
  # 此路径需要为绝对路径，并且next-terminal和guacd都能访问到
  drive: '/usr/local/next-terminal/data/drive'

sshd:
  enable: false
  addr: 0.0.0.0:8089
  key: ~/.ssh/id_rsa