version: '3.8'

services:
  guacd:
    container_name: guacd
    image: fightroad/guacd:latest
    volumes:
      - /opt/docker/next-terminal/data:/usr/local/next-terminal/data
    restart: unless-stopped
    networks:
      - next-terminal

  next-terminal:
    container_name: next-terminal
    image: fightroad/next-terminal:latest
    environment:
      - DB=sqlite
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
    ports:
      - "8088:8088" # Web管理界面
      - "8089:8089" # SSH Server 端口 (可选)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/next-terminal/data:/usr/local/next-terminal/data
      - /opt/docker/next-terminal/logs:/usr/local/next-terminal/logs
    restart: unless-stopped
    depends_on:
      - guacd
    networks:
      - next-terminal

networks:
  next-terminal:
    driver: bridge

